revision/apps/me/urls.py
# -*- coding: UTF-8 -*-
from django.conf.urls import patterns, url
from django.views.generic import TemplateView
from django.contrib.auth.decorators import login_required

from .views import (ConfirmAccountView,
                    ChangePasswordView,

                    ConfirmPasswordChangeRequest,
                    ConfirmEmailChangeRequest,

                    ConfirmEmailValidationRequest,
                    SendEmailValidationRequest,

                    PaymentListView,
                    PlanListView,
                    PlanChangeView,
                    AccountCancelView,
                    WelcomeView,

                    AccountSettingsView,
                    LawyerLetterheadView)


urlpatterns = patterns(
    '',
    url(r'^email_not_validated/$', login_required(TemplateView.as_view(template_name='me/email-validation-pending.html')), name='email-not-validated'),
    url(r'^email_not_validated/send/$', login_required(SendEmailValidationRequest.as_view()), name='send-email-validation-request'),
    url(r'^email_confirmed/(?P<token>.*)/$', ConfirmEmailValidationRequest.as_view(), name='confirm-email-address'),

    url(r'^email_change_confirmed/(?P<token>.*)/$', ConfirmEmailChangeRequest.as_view(), name='confirm-email-change'),
    url(r'^password_change_confirmed/(?P<token>.*)/$', ConfirmPasswordChangeRequest.as_view(), name='confirm-password-change'),

    url(r'^payments/$', login_required(PaymentListView.as_view()), name='payment-list'),
    url(r'^plans/(?P<plan>[a-z0-9_-]{1,25})/$', login_required(PlanChangeView.as_view()), name='plan-change'),
    url(r'^plans/$', login_required(PlanListView.as_view()), name='plan-list'),
    url(r'^welcome/$', login_required(WelcomeView.as_view()), name='welcome'),

    url(r'^settings/letterhead/$', login_required(LawyerLetterheadView.as_view()), name='letterhead'),
    url(r'^settings/confirm/$', login_required(ConfirmAccountView.as_view()), name='confirm-account'),
    url(r'^settings/change-password/$', login_required(ChangePasswordView.as_view()), name='change-password'),

    url(r'^settings/$', login_required(AccountSettingsView.as_view()), name='settings'),

    url(r'^cancel/$', login_required(AccountCancelView.as_view()), name='cancel'),
)

revision/apps/project/urls.py
# -*- coding: utf-8 -*-
from django.conf.urls import patterns, url
from django.contrib.auth.decorators import login_required

from .views import (ProjectListView,
                    ProjectCreateView,
                    ProjectDetailView,
                    ProjectChronicleView)
from .views import (VideoSubtitleView,)


urlpatterns = patterns('',
    url(r'^(?P<slug>[\w-]+)/chronicle/$', login_required(ProjectChronicleView.as_view()), name='chronicle'),
    url(r'^(?P<slug>[\w-]+)/(?P<version_slug>[\d\w-]+)/$', login_required(ProjectDetailView.as_view()), name='with_video_detail'),
    url(r'^(?P<slug>[\w-]+)/(?P<version_slug>[\d\w-]+)/subtitles/$', login_required(VideoSubtitleView.as_view()), name='video_subtitles_url'),

    url(r'^create/$', login_required(ProjectCreateView.as_view()), name='create'),
    url(r'^(?P<slug>[\w-]+)/$', login_required(ProjectDetailView.as_view()), name='detail'),

    url(r'^$', login_required(ProjectListView.as_view()), name='list'),
)

revision/urls.py
# -*- coding: utf-8 -*-
from django.conf import settings
from django.conf.urls.static import static
from django.conf.urls import patterns, include, url

from django.views.generic import TemplateView

from django.contrib import admin
admin.autodiscover()

urlpatterns = patterns('',
    url(r'^admin/', include(admin.site.urls)),

    url(r'^api/v1/', include('revision.api.urls')),

    url(r'^me/password/', include('password_reset.urls')),
    url(r'^me/', include('revision.apps.me.urls', namespace='me')),

    # Payments
    url(r'^payments/', include('payments.urls')),

    url(r'^pub/', include('revision.apps.publish.urls', namespace='publish')),
    url(r'^p/', include('revision.apps.project.urls', namespace='project')),
    url(r'^', include('revision.apps.public.urls', namespace='public')),
)

if settings.DEBUG is True:
    # Add the MEDIA_URL to the dev environment
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

revision/apps/project/forms.py
# -*- coding: utf-8 -*-
from django import forms

from .models import (Project, Video,)

from crispy_forms.helper import FormHelper, Layout
from crispy_forms.layout import Button, Field, Layout, HTML, Fieldset, Div, ButtonHolder, Submit
from parsley.decorators import parsleyfy


@parsleyfy
class ProjectForm(forms.ModelForm):

    client = forms.CharField(
        error_messages={
            'required': "Client name can not be blank."
        },
        help_text='',
        label='Client name',
        required=True,
        max_length=200,
        widget=forms.TextInput(attrs={
            'autocomplete': 'off',
            'placeholder': 'Acme Inc',
            'size': '40',
            # Typeahead
            'data-items': '4',
            'data-provide': 'typeahead',
            'data-source': '[]'
        })
    )

    class Meta:
        model = Project
        exclude = ('slug', 'collaborators', 'data',)

    def __init__(self, *args, **kwargs):
        self.helper = FormHelper()
        self.helper.attrs = {
            'id': 'create-project-form',
            'parsley-validate': ''
        }
        self.helper.form_show_errors = False

        self.helper.layout = Layout(
            HTML('{% include "partials/form-errors.html" with form=form %}'),
            Fieldset(
                '',
                Div(
                    Field('name', css_class=''),
                    css_class='form-name clearfix'
                ),
                Field('client'),
            ),
            ButtonHolder(
                Submit('submit', 'Create')
            )
        )
        super(ProjectForm, self).__init__(*args, **kwargs)


@parsleyfy
class VideoForm(forms.ModelForm):
    class Meta:
        exclude = ('project', 'video_type', 'data',)
        model = Video

revision/apps/project/api/views.py
# -*- coding: utf-8 -*-
from django.conf import settings

from rest_framework import viewsets
from rest_framework import generics
from rest_framework.views import APIView
from rest_framework.response import Response
from rest_framework import status as http_status
from rest_framework.renderers import StaticHTMLRenderer

from revision.decorators import (mutable_request, valid_request_filesize)

from revision.apps.client.models import Client

from ..models import (Project,
                      Video,
                      ProjectCollaborator)
from .serializers import (ProjectSerializer,
                          VideoSerializer,
                          CommentSerializer,)

import urllib2
import base64
import hmac
import sha


class ProjectViewSet(viewsets.ModelViewSet):
    """
    """
    queryset = Project.objects.all()
    serializer_class = ProjectSerializer
    lookup_field = 'slug'

    def pre_save(self, obj):
        client_name = self.request.POST.get('client', None)
        if client_name:
            client, is_new = Client.objects.get_or_create(name=client_name, owner=self.request.user)
            obj.client = client

        return super(ProjectViewSet, self).pre_save(obj=obj)

    def post_save(self, obj, created):
        collaborator, is_new = ProjectCollaborator.objects.get_or_create(user=self.request.user, project=obj)
        return super(ProjectViewSet, self).post_save(obj, created=created)


class ProjectUploadVideoEndpoint(generics.CreateAPIView):
    """
    Upload a video to a project
    """
    queryset = Project.objects.all()
    serializer_class = VideoSerializer
    lookup_field = 'slug'

    @mutable_request
    @valid_request_filesize
    def create(self, request, **kwargs):
        self.project = self.get_object()
        project = ProjectSerializer(self.project).data
        request_data = request.DATA.copy()

        request_data.update({
            'project': project.get('url'),
            'video_url': urllib2.unquote(request_data.get('video_url'))
        })
        serializer = self.get_serializer(data=request_data, files=request.FILES)

        if serializer.is_valid():
            self.pre_save(serializer.object)
            self.object = serializer.save(force_insert=True)
            self.post_save(self.object, created=True)

            headers = self.get_success_headers(serializer.data)
            return Response(serializer.data, status=http_status.HTTP_201_CREATED,
                            headers=headers)

        return Response(serializer.errors, status=http_status.HTTP_400_BAD_REQUEST)

    def post_save(self, obj, created):
        """
        extract just the s3 key name from the url
        """
        # arse into parts
        video_url_parts = urllib2.urlparse.urlparse(obj.video_url)
        # remove the bucket name
        video_url_path = video_url_parts.path.replace('/%s/' % settings.AWS_STORAGE_BUCKET_NAME, '')

        self.object.video = video_url_path  # save the s3 url path to file object
        obj.save(update_fields=['video'])

        return super(ProjectUploadVideoEndpoint, self).post_save(obj, created=created)


class VideoViewSet(viewsets.ModelViewSet):
    """
    """
    queryset = Video.objects.all()
    serializer_class = VideoSerializer
    lookup_field = 'slug'


class VideoCommentsEndpoint(generics.ListCreateAPIView):
    """
    Comments for a specific video
    """
    lookup_field = 'slug'
    lookup_url_kwarg = 'slug'
    queryset = Video.objects.all()
    serializer_class = VideoSerializer
    paginate_by = 100
    allowed_methods = ('get', 'post', 'options', 'head',)

    def list(self, request, **kwargs):
        self.object = self.get_object()
        serializer = CommentSerializer
        return Response(serializer([item for item in self.object.comments_by_id_reversed if item.get('is_deleted', False) is False], many=True).data)

    def create(self, request, **kwargs):
        self.object = self.get_object()
        comment = CommentSerializer(data=request.DATA)
        if comment.is_valid() is True:
            data = comment.data.copy()

            self.object.add_comment(**data)
            self.object.save(update_fields=['data'])

            # the comment is created via a signal, so we do NOT have the comment-object with its id directly.
            return Response(self.object.comments[-1], status=http_status.HTTP_201_CREATED)
        else:
            return Response(status=http_status.HTTP_400_BAD_REQUEST, data={'errors': comment.errors})


class VideoCommentDetailEndpoint(generics.RetrieveUpdateDestroyAPIView):
    """
    A specific single Comment for a specific video
    """
    lookup_field = 'slug'
    lookup_url_kwarg = 'slug'
    queryset = Video.objects.all()
    serializer_class = VideoSerializer
    allowed_methods = ('get', 'patch', 'delete', 'options', 'head',)

    @property
    def pk(self):
        return int(self.kwargs.get('pk')) - 1 ## minus 1 to account for list index

    def retrieve(self, request, **kwargs):
        self.object = self.get_object()
        comment = CommentSerializer(self.object.comments[self.pk])
        return Response(comment.data, status=http_status.HTTP_200_OK)

    def update(self, request, **kwargs):
        self.object = self.get_object()

        try:
            data = self.object.comments[self.pk]
        except IndexError:
            return Response(status=http_status.HTTP_404_NOT_FOUND, data={'errors': 'Comment %d: Does not exist' % self.pk})

        data.update({
            'comment': request.DATA.get('comment', data.get('comment')),  # allow update of only is_deleted items without changing comment
            'is_deleted': request.DATA.get('is_deleted', data.get('is_deleted', False)),  # allow update of is_deleted items
            'secs': int(self.request.DATA.get('secs', 0)),
        })
        comment = CommentSerializer(data, data=data)

        if comment.is_valid() is True:
            self.object.comments[self.pk] = comment.data
            self.object.save(update_fields=['data'])
            return Response(comment.data, status=http_status.HTTP_200_OK)
        else:
            return Response(status=http_status.HTTP_400_BAD_REQUEST, data={'errors': comment.errors})

    def destroy(self, request, **kwargs):
        self.object = self.get_object()
        pk = self.pk + 1  # account for - 1
        try:
            index, data = [(index, c.copy()) for index, c in enumerate(self.object.comments) if c.get('pk') == pk][0]
        except IndexError:
            return Response(status=http_status.HTTP_404_NOT_FOUND, data={'errors': 'Comment %d: Does not exist' % self.pk})

        data.update({
            'is_deleted': True
        })
        comment = CommentSerializer(data, data=data)

        if comment.is_valid() is True:
            # copy the comments so we can modify them
            comments = self.object.comments
            # update the copy
            comments[index] = comment.data
            # set the new comments
            self.object.comments = comments
            # resave
            self.object.save(update_fields=['data'])

            return Response(comment.data, status=http_status.HTTP_200_OK)

        else:
            return Response(status=http_status.HTTP_400_BAD_REQUEST, data={'errors': comment.errors})


class S3SignatureEndpoint(APIView):
    """
    Provide a signed key for the sending object
    """
    renderer_classes = (StaticHTMLRenderer,)

    def get(self, request, **kwargs):
        to_sign = str(request.GET.get('to_sign'))
        signature = base64.b64encode(hmac.new(settings.AWS_SECRET_ACCESS_KEY, to_sign, sha).digest())

        return Response(signature, status=http_status.HTTP_200_OK)

revision/apps/project/views.py
# -*- coding: utf-8 -*-
from django.views.generic import (CreateView,
                                  DetailView,
                                  ListView,)

from django.views.generic.edit import FormMixin

from django.utils.safestring import mark_safe

from rest_framework.renderers import JSONRenderer

from .api.serializers import (ProjectSerializer,
                              VideoSerializer,
                              CommentSerializer)
from .forms import ProjectForm
from .models import Project, Video


class ProjectListView(ListView,
                      FormMixin):
    model = Project
    form_class = ProjectForm

    def get_context_data(self, **kwargs):
        kwargs = super(ProjectListView, self).get_context_data(**kwargs)
        kwargs.update({
            'form': self.get_form(form_class=self.form_class)
        })
        return kwargs
    def get_queryset(self, **kwargs):
        #queryset = self.model._default_manager.all()
        queryset = self.model._default_manager.filter(collaborators__in=[self.request.user])
        return queryset

    @property
    def project_json(self):
        return JSONRenderer().render(ProjectSerializer(self.get_queryset(), many=True).data)


class ProjectCreateView(CreateView):
    model = Project
    form_class = ProjectForm


class ProjectDetailView(DetailView):
    model = Project

    @property
    def project_json(self):
        return JSONRenderer().render(ProjectSerializer(self.object).data)

    @property
    def video_json(self):
        return JSONRenderer().render(VideoSerializer(self.current_video).data)

    @property
    def current_video(self):
        version_slug = self.kwargs.get('version_slug', None)
        self._current_video = self.object.video_set.get(slug=version_slug) if version_slug is not None else self.object.video_set.all().first()
        return self._current_video


class VideoSubtitleView(ProjectDetailView):
    template_name = 'project/video_subtitles.html'

    @property
    def subtitles(self):
        self.object = self.get_object()
        subtitles = self.current_video.comments#[s for s in self.current_video.comments if s.get('comment_type') == 'subtitle']

        for i, s in enumerate(subtitles):
            progress = float(s.get('progress'))
            subtitle_start_progress = Video.secs_to_stamp(progress)

            delay_secs = int(s.get('secs', 4))
            
            subtitle_end_progress = Video.secs_to_stamp(progress + delay_secs)  # delay 4 seconds @TODO make this configurable
            subtitles[i]['subtitle_range'] = mark_safe('%s --> %s' % (subtitle_start_progress, subtitle_end_progress))

        return subtitles


class ProjectChronicleView(ProjectDetailView):
    model = Project
    template_name = 'project/project_chronicle.html'

    @property
    def project_comments_json(self):
        comments = []

        for v in self.object.video_set.all():
            comments += v.comments_by_id_reversed

        return JSONRenderer().render(CommentSerializer(comments, many=True).data)

revision/apps/project/templates/project/project_chronicle.html
{% extends 'project/base.html' %}{% load compressed %}

{% block page_title %}My Test Project{% endblock %}

{% block content %}
{% csrf_token %}
<br/><br/>
<h2>{{ project.name }}:Chronicle</h2>
<div id="project-detail-chronicle"></div>
{% endblock %}


{% block css %}
<link rel="stylesheet" href="//releases.flowplayer.org/5.5.0/skin/minimalist.css">
<style>
.badge > a {
    color:#fff;
}
.control-type-selector {
    width:120px;
}
.input-lg[name=q] {
    height:70px;
    width:440px;
}
</style>
{% endblock css %}

{% block js %}
<script>
'use strict';
/**
* Setup the base javascript objects for our react handler
**/
var Today = moment();

var Project = {{ view.project_json|safe|default:'{}' }};

var Video = {{ view.video_json|safe|default:'{}' }};

var Comments = {{ view.project_comments_json|safe|default:'[]' }};
</script>

{% compressed_js 'project_chronicle' %}

{% endblock js %}

{% block footer %}{% endblock %}

revision/apps/project/templates/project/project_detail.html
{% extends 'project/base.html' %}{% load compressed revision_tags %}

{% block page_title %}{{ project.name }}{% endblock %}

{% block jumbo %}
{% csrf_token %}
<div id="project-detail-base"></div>
<div id="video-timeline"></div>
{% endblock %}

{% block content %}
<div class="row">
    <div id="project-detail-collaborators" class="col-md-4"></div>

    <div class="col-md-4">
      <h2>Export</h2>
      <p>Export the project to dropbox, this will export the video, a Final Cut Pro XML file as well as an activity stream document (activity.html) which allows you to search comments</p>
      <p><a class="btn btn-primary" href="#" role="button">Export &raquo;</a></p>
    </div>

</div>

<div id="modal-keyboard-help" class="modal fade bs-example-modal-lg" tabindex="-1" role="dialog" aria-labelledby="modal-keyboard-help" aria-hidden="true">
  <div class="modal-dialog modal-lg">
    <div class="modal-content">
        <div class="modal-header">
            <button type="button" class="close" data-dismiss="modal"><span aria-hidden="true">&times;</span><span class="sr-only">Close</span></button>
            <h4 class="modal-title" id="myModalLabel">Keyboard controls</h4>
        </div>
        <div class="modal-body">
          <div class="row">
              <div class="col-md-4">
                  <small>
                  <ul>
                      <li><b>p</b>: Play</li>
                      <li><b>s</b>: Pause</li>
                  </ul>
                  </small>
              </div>
              <div class="col-md-4">
                  <small>
                  <ul>
                      <li><b>c</b>: Add Comment - stops the player</li>
                      <li><b>k</b>: Add Sketch - stops the player</li>
                      <li><b>t</b>: Add Sub-Title - stops the player</li>
                  </ul>
                  </small>
              </div>
              <div class="col-md-4">
                  <small>
                  <ul>
                      <li><b>command+1</b>: Goto Begin</li>
                      <li><b>command+0</b>: Goto End</li>
                      <li><b>command+x</b>: Goto Next Comment</li>
                      <li><b>command+c</b>: Goto Previous Comment</li>
                  </ul>
                  </small>
              </div>
          </div>

        </div>
    </div>
  </div>
</div>

{% endblock %}


{% block css %}
<link rel="stylesheet" href="//releases.flowplayer.org/5.5.0/skin/minimalist.css">
{% compressed_css 'project' %}
<style>
.badge > a {
    color:#fff;
}
.control-type-selector {
    width:120px;
}
.input-lg[name=comment] {
    height:70px;
}
div.comment-list{
  background-color:#fff;
  overflow-y: scroll;
  height:515px;
}
ul.versions{
  display: inline-block;
  padding:0px 5px;
}
.progress-bar{
  width:0%;
}
/*Blue imp*/
.fileinput-button {
  position: relative;
  overflow: hidden;
}
.fileinput-button input {
  position: absolute;
  top: 0;
  right: 0;
  margin: 0;
  opacity: 0;
  -ms-filter: 'alpha(opacity=0)';
  font-size: 200px;
  direction: ltr;
  cursor: pointer;
}

/* Fixes for IE < 8 */
@media screen\9 {
  .fileinput-button input {
    filter: alpha(opacity=0);
    font-size: 100%;
    height: 100%;
  }
}
</style>
{% compressed_css 'uploader' %}
{% endblock css %}

{% block js %}

{% compressed_js 'resources' %}
{% compressed_js 'uploader' %}

<script>
'use strict';
/**
* Setup the base javascript objects for our react handler
**/
var Today = moment();

var Project = {{ view.project_json|safe|default:'{}' }};

var Video = {{ view.video_json|safe|default:'{}' }};

var Links = {
  'chronicle': "{% url 'project:chronicle' slug=project.slug %}",
  'publish': "{% if view.current_video %}{% url 'publish:settings' slug=view.current_video.slug %}{% endif %}",
  'upload_video': "{% url 'project_upload_video' slug=project.slug %}",
};

var UploaderConfig = {
   signerUrl: "{% url 's3signature' %}",
   aws_key: '{{ AWS_ACCESS_KEY_ID }}',
   bucket: '{{ AWS_STORAGE_BUCKET_NAME }}',
   aws_url: 'https://s3-eu-west-1.amazonaws.com',
   aws_path: 'uploaded_video/'
};

var User = {
  'username': '{{ request.user.username }}',
  'initials': '{{ request.user.get_initials }}',
  'email': '{{ request.user.email }}'
}

/**
* Setup resource slugs
**/
ProjectVideoResource.params.slug = CollaboratorResource.params.slug = Project.slug;
VideoResource.params.video_slug = '{{ view.current_video.slug }}';
CommentResource.params.video_slug = '{{ view.current_video.slug }}';
</script>

{% compressed_js 'project' %}

{% endblock js %}

{% block footer %}
<p>
    <ul class="list-unstyled">
        <li><b>?</b> Press for keyboard shortcuts</li>
    </ul>
</p>
{% endblock %}

revision/apps/project/templates/project/project_list.html
{% extends 'project/base.html' %}{% load compressed crispy_forms_tags %}


{% block content %}

<div id="project-list" class="row"></div>


<div id="modal-project-create" class="modal fade bs-example-modal-lg" tabindex="-1" role="dialog" aria-labelledby="modal-keyboard-help" aria-hidden="true">
  <div class="modal-dialog modal-lg">
    <div class="modal-content">
        <div class="modal-header">
            <button type="button" class="close" data-dismiss="modal"><span aria-hidden="true">&times;</span><span class="sr-only">Close</span></button>
            <h4 class="modal-title" id="myModalLabel">New Project</h4>
        </div>
        <div class="modal-body">
            {% crispy form %}
        </div>
    </div>
  </div>
</div>

{% endblock %}

{% block js %}
<script>
'use strict';
/**
* Setup the base javascript objects for our react handler
**/
var Today = moment();

var Projects = {{ view.project_json|safe|default:'[]' }};

var User = {
  'username': '{{ request.user.username }}',
  'initials': '{{ request.user.get_initials }}',
  'email': '{{ request.user.email }}'
}

var Links = {
    'create_url': "{% url 'project:create' %}",
    'edit_url': null,
};


$('form#create-project-form').on('submit', function ( e ) {
  e.preventDefault();
  var form = $(this);

  ProjectResource.create( form.serialize() ).defer().done(function ( data ) {
    document.location = data.detail_url;
  });
});

</script>
{% compressed_js 'project_list' %}
{% endblock js %}

revision/apps/project/templates/project/video_subtitles.html
WEBVTT FILE
{% for s in view.subtitles %} 
{{ forloop.counter }}
{{ s.subtitle_range }}
{{ s.comment }}
 {% endfor %}