revision/apps/me/urls.py
# -*- coding: UTF-8 -*-
from django.conf.urls import patterns, url
from django.views.generic import TemplateView
from django.contrib.auth.decorators import login_required

from .views import (ConfirmAccountView,
                    ChangePasswordView,

                    ConfirmPasswordChangeRequest,
                    ConfirmEmailChangeRequest,

                    ConfirmEmailValidationRequest,
                    SendEmailValidationRequest,

                    PaymentListView,
                    PlanListView,
                    PlanChangeView,
                    AccountCancelView,
                    WelcomeView,

                    AccountSettingsView,
                    LawyerLetterheadView)


urlpatterns = patterns(
    '',
    url(r'^email_not_validated/$', login_required(TemplateView.as_view(template_name='me/email-validation-pending.html')), name='email-not-validated'),
    url(r'^email_not_validated/send/$', login_required(SendEmailValidationRequest.as_view()), name='send-email-validation-request'),
    url(r'^email_confirmed/(?P<token>.*)/$', ConfirmEmailValidationRequest.as_view(), name='confirm-email-address'),

    url(r'^email_change_confirmed/(?P<token>.*)/$', ConfirmEmailChangeRequest.as_view(), name='confirm-email-change'),
    url(r'^password_change_confirmed/(?P<token>.*)/$', ConfirmPasswordChangeRequest.as_view(), name='confirm-password-change'),

    url(r'^payments/$', login_required(PaymentListView.as_view()), name='payment-list'),
    url(r'^plans/(?P<plan>[a-z0-9_-]{1,25})/$', login_required(PlanChangeView.as_view()), name='plan-change'),
    url(r'^plans/$', login_required(PlanListView.as_view()), name='plan-list'),
    url(r'^welcome/$', login_required(WelcomeView.as_view()), name='welcome'),

    url(r'^settings/letterhead/$', login_required(LawyerLetterheadView.as_view()), name='letterhead'),
    url(r'^settings/confirm/$', login_required(ConfirmAccountView.as_view()), name='confirm-account'),
    url(r'^settings/change-password/$', login_required(ChangePasswordView.as_view()), name='change-password'),

    url(r'^settings/$', login_required(AccountSettingsView.as_view()), name='settings'),

    url(r'^cancel/$', login_required(AccountCancelView.as_view()), name='cancel'),
)

revision/urls.py
# -*- coding: utf-8 -*-
from django.conf import settings
from django.conf.urls.static import static
from django.conf.urls import patterns, include, url

from django.views.generic import TemplateView

from django.contrib import admin
admin.autodiscover()

urlpatterns = patterns('',
    url(r'^admin/', include(admin.site.urls)),

    url(r'^api/v1/', include('revision.api.urls')),

    url(r'^me/password/', include('password_reset.urls')),
    url(r'^me/', include('revision.apps.me.urls', namespace='me')),

    # Payments
    url(r'^payments/', include('payments.urls')),

    url(r'^pub/', include('revision.apps.publish.urls', namespace='publish')),
    url(r'^p/', include('revision.apps.project.urls', namespace='project')),
    url(r'^', include('revision.apps.public.urls', namespace='public')),
)

if settings.DEBUG is True:
    # Add the MEDIA_URL to the dev environment
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

templates/payments/base.html
{% extends "base.html" %}

templates/payments/payment_list.html
{% extends 'payments/base.html' %}

{% block page_title %}Payment History — {{ block.super }}{% endblock%}

{% block content %}
    <div id="plans" class="content">
        <div class="content-header plans-header clearfix">
            <div class="container">
                <div class="col-sm-8 col-sm-offset-2">
                    <h3>Payment History</h3>
                </div>
            </div>
        </div>

        <div class="container">
            <div class="col-sm-8 col-sm-offset-2" role="main">
                <div class="table-responsive">
                    <table class="table table-bordered" style="background-color: white;">
                        <thead>
                            <tr>
                                <th>Date</th>
                                <th>Card</th>
                                <th>Amount</th>
                                <th>&nbsp;</th>
                            </tr>
                        </thead>
                        <tbody>
                            {% for c in object_list %}
                                <tr>
                                    <td>{{ c.charge_created|date:"M d, Y" }}</td>
                                    <td>{{ c.card_kind|upper }}: ************{{ c.card_last_4 }}</td>
                                    <td>{% if c.paid %}USD ${{ c.amount }}{% else %}FAILED{% endif %}</td>
                                    <td class="text-center">
                                        {% if c.paid %}
                                            <span class="fui-check-inverted text-primary"></span>
                                        {% else %}
                                            <span class="fui-cross-inverted text-danger"></span>
                                        {% endif %}
                                    </td>
                                </tr>
                            {% empty %}
                                <tr>
                                    <td colspan="5" class="text-center">No payments yet.</td>
                                </tr>
                            {% endfor %}
                        </tbody>
                    </table>
                </div>
            </div>
        </div>
    </div>
{% endblock %}

templates/payments/plan_change.html
{% extends 'modal.html' %}

{% block content %}
    {{ block.super }}

    <script type="text/javascript">
        $(document).ready(function() {
            var $form = $('#subscribe-form');
            var $errorContainer = $form.find('.form-errors');
            var $errors = $errorContainer.find('.parsley-errors');

            $backdrop = $loader = $spinner = null;
            var startLoader = function() {
                $backdrop = $('<div class="loader-backdrop in" />')
                    .appendTo($(document.body));

                $loader = $('<div class="loader"><div class="loader-dialog"></div></div>')
                    .appendTo($(document.body));

                $spinner = $('<div class="spinner"><div class="bounce1"></div><div class="bounce2"></div><div class="bounce3"></div></div>')
                    .appendTo($loader.find('.loader-dialog'));
            };
            var stopLoader = function() {
                $backdrop.remove();
                $loader.remove();
                $spinner.remove();

                $backdrop = $loader = $spinner = null;
            };

            var errorHandler = function(data) {
                stopLoader();

                var payload = data.responseJSON;
                $errorContainer.find('p').html('There was 1 error with this:');

                $errors.html('').append("\<ul>\<li>" + payload['error']['message'] + "\</li>\</ul>");
                $errorContainer.removeClass('hide');
            };
            var successHandler = function(data) {
                stopLoader();

                if (data['redirect']) {
                    window.location.href = data['url'];
                };
            };

            $form.on('submit', function(e) {
                e.preventDefault();

                $errorContainer.addClass('hide');

                $elem = $form.find('input[name=stripe_token]');
                if ($elem.val() == '') {
                    StripeCheckout.open({
                        allowRememberMe: false,
                        description: '{{ object.description }}',
                        email: '{{ user.email }}',
                        key: '{{ GLOBALS.STRIPE_PUBLIC_KEY }}',
                        name: '{{ object.name }}',
                        panelLabel: 'Subscribe',
                        token: function(token, args) {
                            $form.find('input[name=stripe_token]').val(token.id);

                            startLoader();

                            $.ajax({
                                data: $form.serialize(),
                                dataType: 'json',
                                headers: {
                                    'X-CSRFToken': $form.find('input[name=csrfmiddlewaretoken]').val()
                                },
                                type: $form.attr('method'),
                                url: $form.attr('action'),
                                error: errorHandler,
                                success: successHandler
                            });
                        }
                    });
                } else {
                    startLoader();

                    $.ajax({
                        data: $form.serialize(),
                        dataType: 'json',
                        headers: {
                            'X-CSRFToken': $form.find('input[name=csrfmiddlewaretoken]').val()
                        },
                        type: $form.attr('method'),
                        url: $form.attr('action'),
                        error: errorHandler,
                        success: successHandler
                    });
                };
            });
        });
    </script>
{% endblock %}

templates/payments/plan_list.html
{% extends 'payments/base.html' %}

{% block page_title %}Plans &amp; Billing — {{ block.super }}{% endblock%}

{% block content %}
    <div id="plans" class="content">
        <div class="content-header plans-header clearfix">
            <div class="container">
                <div class="col-sm-6 col-sm-offset-3">
                    <h3>Your Plan</h3>
                </div>
            </div>
        </div>

        <div class="container">
            <div class="col-sm-6 col-sm-offset-3" role="main">
                <div class="row">
                    {% for p in object_list %}
                        <div class="col-md-12">
                            <div class="plan">
                                <img src="{{ STATIC_URL }}images/icons/ticket.svg" alt="{{ p.name }}" class="plan-image big-illustration">
                                <h3 class="plan-title">{{ p.name }}</h3>
                                <h6 class="plan-price">${{ p.price }}/{{ p.interval }}</h6>
                                <p class="plan-description">{{ p.description|safe}}</p>
                                <p class="plan-features">{{ p.features|safe }}</p>
                                {% if user.profile.subscription.plan == p.stripe_plan_id %}
                                    <span class="btn btn-primary btn-wide"><span class="fui-check-inverted"></span>&nbsp;&nbsp;Current Plan</a>
                                {% else %}
                                    <a href="{% url 'me:plan-change' plan=p.stripe_plan_id %}" data-toggle="modal" data-target="#confirm-{{ p.stripe_plan_id }}" class="btn btn-primary btn-hg btn-embossed">Get this plan</a>
                                {% endif %}
                            </div>
                        </div>
                    {% endfor %}
                </div>
            </div>
        </div>
    </div>
{% endblock %}

{% block modals %}
    {% for p in object_list %}
        <div class="modal" id="confirm-{{ p.stripe_plan_id }}"></div>
    {% endfor %}

    <script src="//checkout.stripe.com/checkout.js"></script>
{% endblock %}