revision/apps/me/urls.py
# -*- coding: UTF-8 -*-
from django.conf.urls import patterns, url
from django.views.generic import TemplateView
from django.contrib.auth.decorators import login_required

from .views import (ConfirmAccountView,
                    ChangePasswordView,

                    ConfirmPasswordChangeRequest,
                    ConfirmEmailChangeRequest,

                    ConfirmEmailValidationRequest,
                    SendEmailValidationRequest,

                    PaymentListView,
                    PlanListView,
                    PlanChangeView,
                    AccountCancelView,
                    WelcomeView,

                    AccountSettingsView,
                    LawyerLetterheadView)


urlpatterns = patterns(
    '',
    url(r'^email_not_validated/$', login_required(TemplateView.as_view(template_name='me/email-validation-pending.html')), name='email-not-validated'),
    url(r'^email_not_validated/send/$', login_required(SendEmailValidationRequest.as_view()), name='send-email-validation-request'),
    url(r'^email_confirmed/(?P<token>.*)/$', ConfirmEmailValidationRequest.as_view(), name='confirm-email-address'),

    url(r'^email_change_confirmed/(?P<token>.*)/$', ConfirmEmailChangeRequest.as_view(), name='confirm-email-change'),
    url(r'^password_change_confirmed/(?P<token>.*)/$', ConfirmPasswordChangeRequest.as_view(), name='confirm-password-change'),

    url(r'^payments/$', login_required(PaymentListView.as_view()), name='payment-list'),
    url(r'^plans/(?P<plan>[a-z0-9_-]{1,25})/$', login_required(PlanChangeView.as_view()), name='plan-change'),
    url(r'^plans/$', login_required(PlanListView.as_view()), name='plan-list'),
    url(r'^welcome/$', login_required(WelcomeView.as_view()), name='welcome'),

    url(r'^settings/letterhead/$', login_required(LawyerLetterheadView.as_view()), name='letterhead'),
    url(r'^settings/confirm/$', login_required(ConfirmAccountView.as_view()), name='confirm-account'),
    url(r'^settings/change-password/$', login_required(ChangePasswordView.as_view()), name='change-password'),

    url(r'^settings/$', login_required(AccountSettingsView.as_view()), name='settings'),

    url(r'^cancel/$', login_required(AccountCancelView.as_view()), name='cancel'),
)

revision/apps/project/urls.py
# -*- coding: utf-8 -*-
from django.conf.urls import patterns, url
from django.contrib.auth.decorators import login_required

from .views import (ProjectListView,
                    ProjectCreateView,
                    ProjectDetailView,
                    ProjectChronicleView)
from .views import (VideoSubtitleView,)


urlpatterns = patterns('',
    url(r'^(?P<slug>[\w-]+)/chronicle/$', login_required(ProjectChronicleView.as_view()), name='chronicle'),
    url(r'^(?P<slug>[\w-]+)/(?P<version_slug>[\d\w-]+)/$', login_required(ProjectDetailView.as_view()), name='with_video_detail'),
    url(r'^(?P<slug>[\w-]+)/(?P<version_slug>[\d\w-]+)/subtitles/$', login_required(VideoSubtitleView.as_view()), name='video_subtitles_url'),

    url(r'^create/$', login_required(ProjectCreateView.as_view()), name='create'),
    url(r'^(?P<slug>[\w-]+)/$', login_required(ProjectDetailView.as_view()), name='detail'),

    url(r'^$', login_required(ProjectListView.as_view()), name='list'),
)

revision/urls.py
# -*- coding: utf-8 -*-
from django.conf import settings
from django.conf.urls.static import static
from django.conf.urls import patterns, include, url

from django.views.generic import TemplateView

from django.contrib import admin
admin.autodiscover()

urlpatterns = patterns('',
    url(r'^admin/', include(admin.site.urls)),

    url(r'^api/v1/', include('revision.api.urls')),

    url(r'^me/password/', include('password_reset.urls')),
    url(r'^me/', include('revision.apps.me.urls', namespace='me')),

    # Payments
    url(r'^payments/', include('payments.urls')),

    url(r'^pub/', include('revision.apps.publish.urls', namespace='publish')),
    url(r'^p/', include('revision.apps.project.urls', namespace='project')),
    url(r'^', include('revision.apps.public.urls', namespace='public')),
)

if settings.DEBUG is True:
    # Add the MEDIA_URL to the dev environment
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

templates/base.html
{% extends 'index.html' %}{% load compressed %}

{% block body %}
  <div class="navbar navbar-inverse navbar-fixed-top" role="navigation">
    <div class="container">
      <div class="navbar-header">
        <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target=".navbar-collapse">
          <span class="sr-only">Toggle navigation</span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
        </button>
        <a class="navbar-brand" href="#">Re<span class="label-danger">&gt;</span>ision</a>
      </div>
      <div class="navbar-collapse collapse">
        {% if not user.is_authenticated %}
          <ul class="nav navbar-nav navbar-right">
            <li><a href="{% url 'public:signin' %}">Sign-in</a></li>
            <li><a href="{% url 'public:signup' %}">Sign-up</a></li>
          </ul>
        {% else %}
          <small>{{ user.get_full_name }}</small>
          <ul class="nav navbar-nav navbar-right">
            <li><a href="{% url 'project:list' %}">Projects</a></li>
            <li><a href="{% url 'me:settings' %}">Account</a></li>
            <li class="divider"></li>
            <li><a href="#" class="intercom">Help</a></li>
            <li class="divider"></li>
            <li><a href="{% url 'public:logout' %}">Sign-out</a></li>
          </ul>
        {% endif %}
      </div><!--/.navbar-collapse -->
    </div>
  </div>

  <!-- Main jumbotron for a primary marketing message or call to action -->
  {% block jumbo %}<p>&nbsp;</p>{% endblock %}

  <div class="container">
    {% block content %}{% endblock %}
    <hr>
    <footer>
      {% block footer %}{% endblock %}
      <p>&copy; Company 2014</p>
    </footer>
  </div> <!-- /container -->
{% endblock %}

templates/index.html
{% load compressed %}<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="description" content="{% block page_description %}{% endblock %}">
    <meta name="author" content="{% block page_author %}{% endblock %}">
    <link rel="icon" href="/favicon.ico">

    <title>{% block page_title %}{% endblock %}</title>

    <!-- Bootstrap core CSS -->
    {% compressed_css 'base' %}

    <!-- HTML5 shim and Respond.js IE8 support of HTML5 elements and media queries -->
    <!--[if lt IE 9]>
      {% compressed_js 'base_ie_only' %}
    <![endif]-->
    {% block css %}{% endblock css %}
  </head>

  <body>

    {% block body %}{% endblock %}


    <!-- Bootstrap core JavaScript
    ================================================== -->
    <!-- Placed at the end of the document so the pages load faster -->
    <script src="//ajax.googleapis.com/ajax/libs/jquery/1.11.1/jquery.min.js"></script>
    <script src="//maxcdn.bootstrapcdn.com/bootstrap/3.2.0/js/bootstrap.min.js"></script>
    <script src="//cdnjs.cloudflare.com/ajax/libs/sugar/1.4.1/sugar.min.js"></script>
    <script src="//cdnjs.cloudflare.com/ajax/libs/fuse.js/1.1.7/fuse.min.js"></script>
    <script src="//cdnjs.cloudflare.com/ajax/libs/moment.js/2.8.2/moment.min.js"></script>
    <script src="//cdnjs.cloudflare.com/ajax/libs/mousetrap/1.4.6/mousetrap.min.js"></script>
    <script src="//cdnjs.cloudflare.com/ajax/libs/parsley.js/2.0.4/parsley.min.js"></script>
    <script src="//releases.flowplayer.org/5.5.0/flowplayer.js"></script>

    {% compressed_js 'base' %}
    {% compressed_js 'react' %}
    {% compressed_js 'resources' %}
    {% if debug %}<script src="{{ STATIC_URL }}js/reactjs/0.11.1/JSXTransformer.js"></script>{% endif %}

    {% block js %}{% endblock %}
  </body>
</html>

templates/modal.html
{% load crispy_forms_tags %}

{% block css %}{% endblock css %}

<div class="modal-dialog">
    <div class="modal-content">
        <div class="modal-header">
            <button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
            <h4 class="modal-title">{% block modal_title %}{{ form.title }}{% endblock %}</h4>
        </div>
        {% block content %}
            {% crispy form %}
        {% endblock %}
    </div>
</div>

{% block js %}
<script type="text/javascript">
// <![CDATA[
(function($) {
    // Re-bind our overloaded version of parsley to any forms
    $('.modal [parsley-validate]').parsley();
})(jQuery);
// ]]>
</script>
{% endblock js %}